on: [push]

jobs:  
  generate-artifacts:
    strategy:
      matrix:
        include:
          - name: a
          - name: b

    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ matrix.name }} > ${{ matrix.name }}.txt
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}.txt

  publish-artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
      - uses: softprops/action-gh-release@v2
        with: 
          tag_name: ${{ github.event.head_commit.message }}
          files: |
            a/a.txt
            b/b.txt
      